main: me.asakura_kukii.siegefishing.main.Main
version: 0.0.2
api-version: 1.18
name: SiegeFishing
commands:
  SiegeFishing:
    description: Main command for SiegeFishing
    aliases: [sf]
permissions:
  siegefishing.admin:
    description: 'Gives access to all admin commands for QAM'
    children:
      siegefishing.debugmessages: true
      siegefishing.reload: true
      siegefishing.item: true
      siegefishing.util: true
softdepend: [ProtocolLib]
author:
   Asakura_kukii